package com.service;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
 * ProductManagementService service = new ProductManagementService();
 * ProductManagementDelegate portType = service.getProductManagementPort();
 * portType.add(...);
 * </pre>
 * 
 * </p>
 * 
 */
@WebServiceClient(name = "ProductManagementService", targetNamespace = "http://service.com/", wsdlLocation = "http://zhangmingshuai-pc:8080/MyJaxService/ProductManagementPort?wsdl")
public class ProductManagementService extends Service {

	private final static URL PRODUCTMANAGEMENTSERVICE_WSDL_LOCATION;
	private final static Logger logger = Logger
			.getLogger(com.service.ProductManagementService.class.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = com.service.ProductManagementService.class
					.getResource(".");
			url = new URL(baseUrl,
					"http://zhangmingshuai-pc:8080/MyJaxService/ProductManagementPort?wsdl");
		} catch (MalformedURLException e) {
			logger
					.warning("Failed to create URL for the wsdl Location: 'http://zhangmingshuai-pc:8080/MyJaxService/ProductManagementPort?wsdl', retrying as a local file");
			logger.warning(e.getMessage());
		}
		PRODUCTMANAGEMENTSERVICE_WSDL_LOCATION = url;
	}

	public ProductManagementService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public ProductManagementService() {
		super(PRODUCTMANAGEMENTSERVICE_WSDL_LOCATION, new QName(
				"http://service.com/", "ProductManagementService"));
	}

	/**
	 * 
	 * @return returns ProductManagementDelegate
	 */
	@WebEndpoint(name = "ProductManagementPort")
	public ProductManagementDelegate getProductManagementPort() {
		return super.getPort(new QName("http://service.com/",
				"ProductManagementPort"), ProductManagementDelegate.class);
	}

}
