package com.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "ProductManagementDelegate", targetNamespace = "http://service.com/")
public interface ProductManagementDelegate {

	/**
	 * 
	 * @param arg3
	 * @param arg2
	 * @param arg1
	 * @param arg0
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "add", targetNamespace = "http://service.com/", className = "com.service.Add")
	@ResponseWrapper(localName = "addResponse", targetNamespace = "http://service.com/", className = "com.service.AddResponse")
	public String add(
			@WebParam(name = "arg0", targetNamespace = "") String arg0,
			@WebParam(name = "arg1", targetNamespace = "") String arg1,
			@WebParam(name = "arg2", targetNamespace = "") String arg2,
			@WebParam(name = "arg3", targetNamespace = "") String arg3);

	/**
	 * 
	 * @param arg0
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "getDescription", targetNamespace = "http://service.com/", className = "com.service.GetDescription")
	@ResponseWrapper(localName = "getDescriptionResponse", targetNamespace = "http://service.com/", className = "com.service.GetDescriptionResponse")
	public String getDescription(
			@WebParam(name = "arg0", targetNamespace = "") String arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "confirm", targetNamespace = "http://service.com/", className = "com.service.Confirm")
	@ResponseWrapper(localName = "confirmResponse", targetNamespace = "http://service.com/", className = "com.service.ConfirmResponse")
	public String confirm(
			@WebParam(name = "arg0", targetNamespace = "") String arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "getCount", targetNamespace = "http://service.com/", className = "com.service.GetCount")
	@ResponseWrapper(localName = "getCountResponse", targetNamespace = "http://service.com/", className = "com.service.GetCountResponse")
	public String getCount(
			@WebParam(name = "arg0", targetNamespace = "") String arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "getOne", targetNamespace = "http://service.com/", className = "com.service.GetOne")
	@ResponseWrapper(localName = "getOneResponse", targetNamespace = "http://service.com/", className = "com.service.GetOneResponse")
	public String getOne(
			@WebParam(name = "arg0", targetNamespace = "") String arg0);

	/**
	 * 
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "getProductList", targetNamespace = "http://service.com/", className = "com.service.GetProductList")
	@ResponseWrapper(localName = "getProductListResponse", targetNamespace = "http://service.com/", className = "com.service.GetProductListResponse")
	public String getProductList();

	/**
	 * 
	 * @param arg0
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "getPrice", targetNamespace = "http://service.com/", className = "com.service.GetPrice")
	@ResponseWrapper(localName = "getPriceResponse", targetNamespace = "http://service.com/", className = "com.service.GetPriceResponse")
	public String getPrice(
			@WebParam(name = "arg0", targetNamespace = "") String arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "buy", targetNamespace = "http://service.com/", className = "com.service.Buy")
	@ResponseWrapper(localName = "buyResponse", targetNamespace = "http://service.com/", className = "com.service.BuyResponse")
	public String buy(@WebParam(name = "arg0", targetNamespace = "") String arg0);

}
